// BC hospital data derived from Wikipedia "List of hospitals in British Columbia"
// health_authority values match the HEALTH_AUTHORITIES constants in ShiftConfiguration
export const BC_HOSPITALS = [
  // Vancouver Coastal Health (VCH)
  { name: 'Vancouver General Hospital', acronym: 'VGH', health_authority: 'VCH' },
  { name: 'UBC Hospital', acronym: 'UBCH', health_authority: 'VCH' },
  { name: 'Richmond Hospital', acronym: 'RH', health_authority: 'VCH' },
  { name: 'Lions Gate Hospital', acronym: 'LGH', health_authority: 'VCH' },
  { name: 'Squamish General Hospital', acronym: 'SGH', health_authority: 'VCH' },
  { name: 'Whistler Health Care Centre', acronym: 'WHCC', health_authority: 'VCH' },
  { name: 'Powell River General Hospital', acronym: 'PRGH', health_authority: 'VCH' },
  { name: 'Sechelt Hospital', acronym: 'SH', health_authority: 'VCH' },
  { name: 'Bella Coola General Hospital', acronym: 'BCGH', health_authority: 'VCH' },
  { name: 'Bella Bella Community Hospital', acronym: 'BBCH', health_authority: 'VCH' },
  { name: 'Gibsons Health Unit', acronym: 'GHU', health_authority: 'VCH' },
  { name: 'Pemberton Health Centre', acronym: 'PHCe', health_authority: 'VCH' },
  { name: 'GF Strong Rehabilitation Centre', acronym: 'GFSR', health_authority: 'VCH' },
  { name: 'Mount Saint Joseph Hospital', acronym: 'MSJ', health_authority: 'PHC' },
  { name: "St. Paul's Hospital", acronym: 'SPH', health_authority: 'PHC' },
  { name: "St. Vincent's Hospital", acronym: 'SVH', health_authority: 'PHC' },
  // Fraser Health (FH)
  { name: 'Surrey Memorial Hospital', acronym: 'SMH', health_authority: 'FH' },
  { name: 'Royal Columbian Hospital', acronym: 'RCH', health_authority: 'FH' },
  { name: 'Abbotsford Regional Hospital', acronym: 'ARH', health_authority: 'FH' },
  { name: 'Burnaby Hospital', acronym: 'BH', health_authority: 'FH' },
  { name: 'Delta Hospital', acronym: 'DH', health_authority: 'FH' },
  { name: 'Ridge Meadows Hospital', acronym: 'RMH', health_authority: 'FH' },
  { name: 'Chilliwack General Hospital', acronym: 'CGH', health_authority: 'FH' },
  { name: 'Peace Arch Hospital', acronym: 'PAH', health_authority: 'FH' },
  { name: 'Langley Memorial Hospital', acronym: 'LMH', health_authority: 'FH' },
  { name: 'Mission Memorial Hospital', acronym: 'MMH', health_authority: 'FH' },
  { name: 'Fraser Canyon Hospital', acronym: 'FCH', health_authority: 'FH' },
  { name: 'Squamish General Hospital', acronym: 'SGH', health_authority: 'FH' },
  { name: 'Matsqui-Sumas-Abbotsford General Hospital', acronym: 'MSA', health_authority: 'FH' },
  { name: 'Jim Pattison Outpatient Care and Surgery Centre', acronym: 'JPOC', health_authority: 'FH' },
  { name: 'Fort Langley Community Hospital', acronym: 'FLCH', health_authority: 'FH' },
  // Island Health (VIHA)
  { name: 'Victoria General Hospital', acronym: 'VicGH', health_authority: 'VIHA' },
  { name: 'Royal Jubilee Hospital', acronym: 'RJH', health_authority: 'VIHA' },
  { name: 'Nanaimo Regional General Hospital', acronym: 'NRGH', health_authority: 'VIHA' },
  { name: 'Cowichan District Hospital', acronym: 'CDH', health_authority: 'VIHA' },
  { name: 'Lady Minto Gulf Islands Hospital', acronym: 'LMGI', health_authority: 'VIHA' },
  { name: 'Campbell River & District General Hospital', acronym: 'CRDGH', health_authority: 'VIHA' },
  { name: 'Comox Valley Hospital', acronym: 'CVH', health_authority: 'VIHA' },
  { name: 'Port Hardy Hospital', acronym: 'PHH', health_authority: 'VIHA' },
  { name: 'Port McNeill & District Hospital', acronym: 'PMH', health_authority: 'VIHA' },
  { name: "St. Joseph's General Hospital Comox", acronym: 'SJGH', health_authority: 'VIHA' },
  { name: 'Tofino General Hospital', acronym: 'TGH', health_authority: 'VIHA' },
  { name: 'West Coast General Hospital', acronym: 'WCGH', health_authority: 'VIHA' },
  { name: 'Saanich Peninsula Hospital', acronym: 'SPeH', health_authority: 'VIHA' },
  { name: 'Chemainus Health Care Centre', acronym: 'CHCC', health_authority: 'VIHA' },
  { name: 'Cormorant Island Health Centre', acronym: 'CIHC', health_authority: 'VIHA' },
  { name: 'Galiano Health Care Centre', acronym: 'GHCC', health_authority: 'VIHA' },
  { name: 'Hornby Island Health Centre', acronym: 'HIHC', health_authority: 'VIHA' },
  { name: 'Ladysmith Community Health Centre', acronym: 'LCHC', health_authority: 'VIHA' },
  { name: 'Mayne Island Health Centre', acronym: 'MIHC', health_authority: 'VIHA' },
  { name: 'Pender Island Health Centre', acronym: 'PeIHC', health_authority: 'VIHA' },
  { name: 'Salt Spring Island Community Services', acronym: 'SSICS', health_authority: 'VIHA' },
  { name: 'Saturna Island Medical Clinic', acronym: 'SIMC', health_authority: 'VIHA' },
  // Interior Health (IH)
  { name: 'Kelowna General Hospital', acronym: 'KGH', health_authority: 'IH' },
  { name: 'Royal Inland Hospital', acronym: 'RIH', health_authority: 'IH' },
  { name: 'Penticton Regional Hospital', acronym: 'PRH', health_authority: 'IH' },
  { name: 'Kootenay Boundary Regional Hospital', acronym: 'KBRH', health_authority: 'IH' },
  { name: 'East Kootenay Regional Hospital', acronym: 'EKRH', health_authority: 'IH' },
  { name: 'Vernon Jubilee Hospital', acronym: 'VJH', health_authority: 'IH' },
  { name: 'South Okanagan General Hospital', acronym: 'SOGH', health_authority: 'IH' },
  { name: 'Kamloops Hospital', acronym: 'KamH', health_authority: 'IH' },
  { name: '100 Mile District General Hospital', acronym: '100MGH', health_authority: 'IH' },
  { name: 'Arrow Lakes Hospital', acronym: 'ALH', health_authority: 'IH' },
  { name: 'Ashcroft & District General Hospital', acronym: 'ADGH', health_authority: 'IH' },
  { name: 'Barriere & District Health Centre', acronym: 'BDHC', health_authority: 'IH' },
  { name: 'Boundary Hospital', acronym: 'BouH', health_authority: 'IH' },
  { name: 'Cache Creek Health Centre', acronym: 'CCHC', health_authority: 'IH' },
  { name: 'Cariboo Memorial Hospital', acronym: 'CMH', health_authority: 'IH' },
  { name: 'Chase Health Centre', acronym: 'ChHC', health_authority: 'IH' },
  { name: 'Christina Lake Health Centre', acronym: 'CLHC', health_authority: 'IH' },
  { name: 'Clearwater Health Centre', acronym: 'CwHC', health_authority: 'IH' },
  { name: 'Elk Valley Hospital', acronym: 'EVH', health_authority: 'IH' },
  { name: 'Enderby & District Memorial Hospital', acronym: 'EDMH', health_authority: 'IH' },
  { name: 'Golden & District General Hospital', acronym: 'GDGH', health_authority: 'IH' },
  { name: 'Grand Forks Hospital', acronym: 'GFH', health_authority: 'IH' },
  { name: 'Hedley Health Centre', acronym: 'HHC', health_authority: 'IH' },
  { name: 'Invermere & District Hospital', acronym: 'IDH', health_authority: 'IH' },
  { name: 'Keremeos Health Centre', acronym: 'KerHC', health_authority: 'IH' },
  { name: 'Kimberley Health Centre', acronym: 'KimHC', health_authority: 'IH' },
  { name: 'Lake Country Health Centre', acronym: 'LCHC2', health_authority: 'IH' },
  { name: 'Lillooet Hospital & Health Centre', acronym: 'LHHC', health_authority: 'IH' },
  { name: 'Logan Lake Health Centre', acronym: 'LLHC', health_authority: 'IH' },
  { name: 'Lumby Health Centre', acronym: 'LumHC', health_authority: 'IH' },
  { name: 'Merritt & District Hospital', acronym: 'MDH', health_authority: 'IH' },
  { name: 'Midway Health Centre', acronym: 'MidHC', health_authority: 'IH' },
  { name: 'Nakusp Health Centre', acronym: 'NakHC', health_authority: 'IH' },
  { name: 'New Denver/Slocan Community Health Centre', acronym: 'NDSCHC', health_authority: 'IH' },
  { name: 'Oliver Hospital', acronym: 'OlH', health_authority: 'IH' },
  { name: 'Osoyoos Hospital', acronym: 'OsoH', health_authority: 'IH' },
  { name: 'Princeton General Hospital', acronym: 'PGH', health_authority: 'IH' },
  { name: 'Revelstoke Queen Victoria Hospital', acronym: 'RQVH', health_authority: 'IH' },
  { name: 'Salmon Arm Hospital', acronym: 'SAH', health_authority: 'IH' },
  { name: 'Shuswap Lake General Hospital', acronym: 'SLGH', health_authority: 'IH' },
  { name: 'Sparwood General Hospital', acronym: 'SpGH', health_authority: 'IH' },
  { name: 'Summerland Health Centre', acronym: 'SumHC', health_authority: 'IH' },
  { name: 'Trail Regional Hospital', acronym: 'TRH', health_authority: 'IH' },
  // Northern Health (NH)
  { name: 'University Hospital of Northern BC', acronym: 'UHNBC', health_authority: 'NH' },
  { name: 'Fort St. John Hospital', acronym: 'FSJH', health_authority: 'NH' },
  { name: 'G.R. Baker Memorial Hospital', acronym: 'GRBMH', health_authority: 'NH' },
  { name: 'Kitimat General Hospital', acronym: 'KitGH', health_authority: 'NH' },
  { name: 'Mills Memorial Hospital', acronym: 'MMHt', health_authority: 'NH' },
  { name: 'Northern Haida Gwaii Hospital', acronym: 'NHGH', health_authority: 'NH' },
  { name: 'Prince Rupert Regional Hospital', acronym: 'PRRH', health_authority: 'NH' },
  { name: 'Bulkley Valley District Hospital', acronym: 'BVDH', health_authority: 'NH' },
  { name: 'Chetwynd General Hospital', acronym: 'ChetGH', health_authority: 'NH' },
  { name: 'Dawson Creek & District Hospital', acronym: 'DCDH', health_authority: 'NH' },
  { name: 'Fort Nelson General Hospital', acronym: 'FNGH', health_authority: 'NH' },
  { name: 'Fort St. James Health Centre', acronym: 'FSJHC', health_authority: 'NH' },
  { name: 'Houston Health Centre', acronym: 'HouHC', health_authority: 'NH' },
  { name: 'Hudson Hope Health Centre', acronym: 'HHHC', health_authority: 'NH' },
  { name: 'Mackenzie & District Hospital', acronym: 'MADH', health_authority: 'NH' },
  { name: 'McBride & District Hospital', acronym: 'MBH', health_authority: 'NH' },
  { name: 'Queen Charlotte Islands General Hospital', acronym: 'QCIGH', health_authority: 'NH' },
  { name: 'Sparwood General Hospital NH', acronym: 'SpGHN', health_authority: 'NH' },
  { name: 'Stewart Health Centre', acronym: 'SteHC', health_authority: 'NH' },
  { name: 'Tumbler Ridge Health Centre', acronym: 'TRHC', health_authority: 'NH' },
  { name: 'Vanderhoof Health Centre', acronym: 'VanHC', health_authority: 'NH' },
  // Provincial Health Services Authority (PHSA)
  { name: "BC Children's Hospital", acronym: 'BCCH', health_authority: 'PHSA' },
  { name: "BC Women's Hospital & Health Centre", acronym: 'BCWH', health_authority: 'PHSA' },
  { name: 'BC Cancer Agency Vancouver Centre', acronym: 'BCCA', health_authority: 'PHSA' },
  { name: "BC Children's Hospital Research Institute", acronym: 'BCCHRI', health_authority: 'PHSA' },
  { name: 'Riverview Hospital', acronym: 'RivH', health_authority: 'PHSA' },
  { name: 'BC Mental Health & Substance Use Services', acronym: 'BCMHSUS', health_authority: 'PHSA' },
  { name: 'Forensic Psychiatric Hospital', acronym: 'FPH', health_authority: 'PHSA' },
];

// Returns suggestions matching the typed value (case-insensitive, by name or acronym)
export function searchHospitals(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return BC_HOSPITALS.filter(
    h => h.name.toLowerCase().includes(q) || h.acronym.toLowerCase().includes(q)
  ).slice(0, 8);
}
